id: IBF30BB45
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:52:42+00:00'
last_modified: '2022-06-07T21:54:42.294693+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20498
  title: མི་དང་མིའི་དབར་འདྲ་མཉམ་མེད་པའི་འབྱུང་རྩ་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    915F:
      image_group_id: I8LS20500
      title: ''
      total_pages: 350
      order: 1
      base_file: 915F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
