id: P004313
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20498
  title: མི་དང་མིའི་དབར་འདྲ་མཉམ་མེད་པའི་འབྱུང་རྩ་གླེང་བ།
  author: ''
  volumes:
    7731059478094335a3253aead3468ac7:
      image_group_id: I8LS20500
      title: ''
      volume_number: 1
      total_pages: 350
      base_file: v001.txt
